STATUS_PENDING_APPROVAL = "PENDING_APPROVAL"
STATUS_POSTPONED = "POSTPONED"
STATUS_APPROVED = "APPROVED"
STATUS_AUTO_APPROVED = "AUTO_APPROVED"
STATUS_INSTALL_READY = "INSTALL_READY"
STATUS_AUTO_INSTALL_READY = "AUTO_INSTALL_READY"
STATUS_RESOLVED = "RESOLVED"
STATUS_FAILED_CONFIGURATION = "FAILED_CONFIGURATION"
STATUS_FAILED_REMEDIATION = "FAILED_REMEDIATION"
STATUS_INSTANCE_NOT_FOUND = "INSTANCE_NOT_FOUND"
STATUS_MANUAL = "MANUAL"

ACTIVE_STATUSES = (
    STATUS_PENDING_APPROVAL,
    STATUS_MANUAL,
    STATUS_POSTPONED,
    STATUS_APPROVED,
    STATUS_AUTO_APPROVED,
    STATUS_INSTALL_READY,
    STATUS_AUTO_INSTALL_READY,
)

REFRESHABLE_ACTIVE_STATUSES = {
    STATUS_PENDING_APPROVAL,
    STATUS_APPROVED,
    STATUS_AUTO_APPROVED,
    STATUS_INSTALL_READY,
    STATUS_AUTO_INSTALL_READY,
}

REASON_UNSUPPORTED_ACTIVE_STATUS = "UNSUPPORTED_ACTIVE_STATUS"
REASON_INSTANCE_COMPLIANT = "INSTANCE_COMPLIANT"
REASON_INSTANCE_COMPLIANT_APPROVAL_TAG_REMOVED = (
    "INSTANCE_COMPLIANT_APPROVAL_TAG_REMOVED"
)
REASON_FAILED_TO_REMOVE_PATCH_INSTALL_APPROVAL_TAG = (
    "FAILED_TO_REMOVE_PATCH_INSTALL_APPROVAL_TAG"
)
REASON_INSTANCE_COMPLIANT_WITHOUT_ACTIVE_REQUEST = (
    "INSTANCE_COMPLIANT_WITHOUT_ACTIVE_REQUEST"
)
REASON_INSTANCE_DETAILS_MISSING_WITHOUT_ACTIVE_REQUEST = (
    "INSTANCE_DETAILS_MISSING_WITHOUT_ACTIVE_REQUEST"
)
REASON_INSTANCE_NOT_FOUND = "INSTANCE_NOT_FOUND"
REASON_INSTANCE_DETAILS_MISSING = "INSTANCE_DETAILS_MISSING"
REASON_PATCH_MANAGEMENT_DISABLED = "PATCH_MANAGEMENT_DISABLED"
REASON_STATUS_UNCHANGED_METADATA_REFRESH = "STATUS_UNCHANGED_METADATA_REFRESH"
REASON_MISSING_PATCH_INSTALL_WINDOW = "MISSING_PATCH_INSTALL_WINDOW"
REASON_NON_COMPLIANT_REQUIRES_INSTALL_APPROVAL = (
    "NON_COMPLIANT_REQUIRES_INSTALL_APPROVAL"
)
REASON_POSTPONEMENT_EXPIRED = "POSTPONEMENT_EXPIRED"
REASON_POSTPONEMENT_STILL_ACTIVE = "POSTPONEMENT_STILL_ACTIVE"
REASON_POSTPONED_WITHOUT_COUNT = "POSTPONED_WITHOUT_COUNT"
REASON_POSTPONE_LIMIT_EXCEEDED = "POSTPONE_LIMIT_EXCEEDED"
REASON_POSTPONED_WITHOUT_DEADLINE = "POSTPONED_WITHOUT_DEADLINE"
REASON_INSTALL_WINDOW_NOT_REACHED = "INSTALL_WINDOW_NOT_REACHED"
REASON_INSTALL_GRACE_PERIOD_ACTIVE = "INSTALL_GRACE_PERIOD_ACTIVE"
REASON_INSTALL_DID_NOT_REMEDIATE_COMPLIANCE = "INSTALL_DID_NOT_REMEDIATE_COMPLIANCE"
