STATUS_APPROVED = "APPROVED"
STATUS_AUTO_APPROVED = "AUTO_APPROVED"
STATUS_INSTALL_READY = "INSTALL_READY"
STATUS_AUTO_INSTALL_READY = "AUTO_INSTALL_READY"

EXECUTABLE_STATUSES = {STATUS_APPROVED, STATUS_AUTO_APPROVED}
READY_STATUS_BY_EXECUTABLE = {
    STATUS_APPROVED: STATUS_INSTALL_READY,
    STATUS_AUTO_APPROVED: STATUS_AUTO_INSTALL_READY,
}

REASON_UNSUPPORTED_EVENT_NAME = "UNSUPPORTED_EVENT_NAME"
REASON_MISSING_NEW_IMAGE = "MISSING_NEW_IMAGE"
REASON_REQUEST_BELONGS_TO_ANOTHER_REGION = "REQUEST_BELONGS_TO_ANOTHER_REGION"
REASON_STATUS_NOT_ELIGIBLE_FOR_EXECUTION = "STATUS_NOT_ELIGIBLE_FOR_EXECUTION"
REASON_STATUS_DID_NOT_CHANGE = "STATUS_DID_NOT_CHANGE"
REASON_UNHANDLED_EXCEPTION = "UNHANDLED_EXCEPTION"
REASON_FAILED_TO_QUERY_LATEST_REQUEST = "FAILED_TO_QUERY_LATEST_REQUEST"
REASON_LATEST_REQUEST_NOT_FOUND = "LATEST_REQUEST_NOT_FOUND"
REASON_OUTDATED_STREAM_RECORD = "OUTDATED_STREAM_RECORD"
REASON_LATEST_REQUEST_BELONGS_TO_ANOTHER_REGION = "LATEST_REQUEST_BELONGS_TO_ANOTHER_REGION"
REASON_REQUEST_ALREADY_MOVED = "REQUEST_ALREADY_MOVED"
REASON_MISSING_INSTANCE_ID = "MISSING_INSTANCE_ID"
REASON_PATCH_INSTALL_APPROVAL_TAG_APPLIED = "PATCH_INSTALL_APPROVAL_TAG_APPLIED"
REASON_FAILED_TO_APPLY_PATCH_INSTALL_APPROVAL_TAG = "FAILED_TO_APPLY_PATCH_INSTALL_APPROVAL_TAG"
REASON_FAILED_TO_MARK_REQUEST_READY_FOR_INSTALL = "FAILED_TO_MARK_REQUEST_READY_FOR_INSTALL"
REASON_REQUEST_READY_FOR_INSTALL = "REQUEST_READY_FOR_INSTALL"
REASON_EXPECTED_INSTALL_WINDOW_CAPTURED = "EXPECTED_INSTALL_WINDOW_CAPTURED"
